### ISSUE TITLE
Does this support UWP 10?

### ISSUE THREAD

**Issue by stwktw** [keijiro/MidiJack#25]
Hi!

Does this support UWP 10?

Can we solve this issue?
My UWP 10 device can't found dll.  

error message.
DllNotFoundException: Unable to load DLL 'MidiJackPlugin': The specified procedure could not be found. (Exception from HRESULT: 0x8007007F)
   at MidiJack.MidiDriver.DequeueIncomingData()
   at MidiJack.MidiDriver.Update()
   at MidiJack.MidiDriver.UpdateIfNeeded()
   at MidiJack.MidiDriver.GetKey(MidiChannel channel, Int32 noteNumber)
   at NoteIndicator.Update()
   at NoteIndicator.$Invoke5Update(Int64 instance, Int64* args)
   at UnityEngine.Internal.$MethodUtility.InvokeMethod(Int64 instance, Int64* args, IntPtr method) 
(Filename: <Unknown> Line: 0)

**Comment by keijiro** [comment]
MIDIJack doesn't support UWP at the moment.

**Comment by danjaco** [comment]
+1 support this feature request. Using the UWP API automatically provides Bluetooth LE Midi support. I think with aftermarket dongles e.g. Yamaha MD-BT01/UD-BT01 and dedicated BT hardware this is going to be the future of Midi.

https://blogs.windows.com/buildingapps/2016/09/21/midi-enhancements-in-windows-10/

**Comment by keijiro** [comment]
Just out of curiosity, why are you using UWP not native Windows Standalone? HoloLens?

**Comment by danjaco** [comment]
I don't really care about the UWP if there is an easier way to get BLE support?

**Comment by keijiro** [comment]
Aha. Thanks for clarification. I'll look for both possibilities.

**Comment by danjaco** [comment]
Great, thanks! I can think of some interesting possibilities for a wireless Midi control/Hololens combo (including some that aren't musical). For me, not in the near future though.

**Comment by pshannon1000** [comment]
Just wondering if there's an update on this at all - am I able to use MidiJack in a UWP build?

Thank you!

**Comment by keijiro** [comment]
@pshannon1000 No.
